### ISSUE TITLE
Build fails on systems without AVX512

### ISSUE THREAD

**Issue by noisymime** [Chia-Network/chiapos#219]
Low priority, but currently the Blake3 code will not compile on x64 systems without the AVX2 / AVX512 instructions, at least with the following test system. 

**Test system**
System: MacPro 5,1 
CPU: Xeon Westmere W3680
OS: macOS 10.14

**Compile errors**
```
/Users/xxxx/Documents/tmp/chiapos/src/b3/blake3_avx2.c:20:42: error: always_inline function '_mm256_set1_epi32' requires target feature 'xsave', but would be inlined into function 'set1' that is
      compiled without support for 'xsave'
INLINE __m256i set1(uint32_t x) { return _mm256_set1_epi32((int32_t)x); }
```

This above is repeated for all the `set`, `and`, `cmpgt`, `xor` etc functions and also in the 512 files:
```
/Users/xxxx/Documents/tmp/chiapos/src/b3/blake3_avx512.c:1115:3: error: always_inline function '_mm256_mask_storeu_epi32' requires target feature 'sse4.2', but would be inlined into function
      'blake3_hash16_avx512' that is compiled without support for 'sse4.2'
  _mm256_mask_storeu_epi32(&out[0 * sizeof(__m256i)], (__mmask8)-1, _mm512_castsi512_si256(padded[0]));
```

I've confirmed that the `get_cpu_features()` function is currently identifying that AVX is not available:
```
SSE2: 1
SSE3: 2
SSE4.1: 4
AVX: 0
AVX2: 0
AVX512F: 0
AVX512VL: 0
```

However the compile itself is still including the instructions that are not available. 

**Workaround**
The build can be made to work by removing the `src/b3/blake3_avx2.c` and  `src/b3/blake3_avx512.c` files from `BLAKE3_SRC` in `CMakeLists.txt` and then: 
```
#define BLAKE3_NO_AVX512
#define BLAKE3_NO_AVX2
```

Not necessarily expecting a fix on this, but it looked like there had been some work into trying to do CPU feature identification so wanted to call it out.

**Comment by emlowe** [comment]
I'm able to build without modifications on macOS 10.14 on a SandyBridge-EP processor that has AVX but not AVX2 or others.

**Comment by emlowe** [comment]
Closing issue - I'm also able to build on macOS 10.15 on i7-3840QM also with AVX but not anything else.
If this issue remains, it likely is on Westmere or older CPUs

**Comment by Hardcore-fs** [comment]
it is not the CPU.......
it is the CLANG & Xcode...
The clang was a modified version that will not even compile AVX512 instructions, it has no knowledge of them.
was done by apple to prevent developers using them incorrectly.

10.14 onwards uses a different clang & xcode that DOES recognize the instructions, even the CPU does not.
so it allows the assembly to be processed by xcode but not implemented in the CPU.

wrap or don't compile on anything less than 10.14

**Comment by hoffmang9** [comment]
This is why we use Gulrak and why we only support Mojave or newer.
